#!/bin/bash

# curl https://raw.githubusercontent.com/vitalij-vladimirov/git-config/master/prepare-commit-msg > .git/hooks/prepare-commit-msg && chmod u+x .git/hooks/prepare-commit-msg

BRANCHES_TO_SKIP=(master dev development testing test prod production)

BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_NAME="${BRANCH_NAME##*/}"

IFS='-' read -r -a BRANCH_NAME_PART <<< "$BRANCH_NAME"

if [ ${#BRANCH_NAME_PART[@]} -ge 2 ] && [ ${#BRANCH_NAME_PART[0]} -le 3 ] && [ -n "${BRANCH_NAME_PART[1]}" ]; then
  BRANCH_ID="${BRANCH_NAME_PART[0]}"-"${BRANCH_NAME_PART[1]}"

  BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")
  BRANCH_IN_COMMIT=$(grep -c "\[$BRANCH_ID\]" $1)

  if [ -n "$BRANCH_ID" ] && ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then 
    sed -i.bak -e "1s/^/$BRANCH_ID: /" $1
  fi
fi;
